// Generated by https://quicktype.io

export interface AkumaResponse {
    ok:     boolean;
    frutas: Fruta[];
}

export interface Fruta {
    _id:         string;
    nombreFruta: string;
    usuario:     string;
    tipo:        string;
    imagen:      string;
    // eslint-disable-next-line @typescript-eslint/naming-convention
    __v:         number;
}

// export enum Tipo {
//     Logia = "Logia",
//     Paramecia = "Paramecia",
//     Zoan = "Zoan",
//     ZoanMitologica = "Zoan mitologica",
// }
